export const incidents = [
  {
    id: 1,
    name: 'Пример',
    firstPriority: 'Низкий',
    param: 'authorization_problem_access',
    errors: 10,
    creationDate: '27.03.2024',
    decisionTargetDate: '01.04.2024',
    admin: 'Сиборомин А.В.',
    service: 'Service name',
    connectedIncidents: [],
    secondPriority: 'Связанный',
  },
  {
    id: 2,
    name: 'Пример',
    firstPriority: 'Низкий',
    param: 'authorization_problem_access',
    errors: 39,
    creationDate: '27.03.2024',
    decisionTargetDate: '01.04.2024',
    admin: 'Сиборомин А.В.',
    service: 'Service name',
    connectedIncidents: [],
    secondPriority: '',
  },
  {
    id: 3,
    name: 'Пример',
    firstPriority: 'Низкий',
    param: 'authorization_problem_access',
    errors: 22,
    creationDate: '27.03.2024',
    decisionTargetDate: '01.04.2024',
    admin: 'Сиборомин А.В.',
    service: 'Service name',
    connectedIncidents: [],
    secondPriority: 'Связанный',
  },
  {
    id: 4,
    name: 'Пример',
    firstPriority: 'Средний',
    param: 'authorization_problem_access',
    errors: 91,
    creationDate: '27.03.2024',
    decisionTargetDate: '01.04.2024',
    admin: 'Сиборомин А.В.',
    service: 'Service name',
    connectedIncidents: [],
    secondPriority: 'Корневой',
  },
  {
    id: 5,
    name: 'Пример',
    firstPriority: 'Средний',
    param: 'authorization_problem_access',
    errors: 120,
    creationDate: '27.03.2024',
    decisionTargetDate: '01.04.2024',
    admin: 'Сиборомин А.В.',
    service: 'Service name',
    connectedIncidents: [],
    secondPriority: '',
  },
  {
    id: 6,
    name: 'Пример',
    firstPriority: 'Высокий',
    param: 'authorization_problem_access',
    errors: 290,
    creationDate: '27.03.2024',
    decisionTargetDate: '01.04.2024',
    admin: 'Сиборомин А.В.',
    service: 'Service name',
    connectedIncidents: [],
    secondPriority: '',
  },
  {
    id: 7,
    name: 'Пример',
    firstPriority: 'Критический',
    param: 'authorization_problem_access',
    errors: 420,
    creationDate: '27.03.2024',
    decisionTargetDate: '01.04.2024',
    admin: 'Сиборомин А.В.',
    service: 'Service name',
    connectedIncidents: [],
    secondPriority: 'Корневой',
  },
  {
    id: 8,
    name: 'Пример',
    firstPriority: 'Критический',
    param: 'authorization_problem_access',
    errors: 310,
    creationDate: '27.03.2024',
    decisionTargetDate: '01.04.2024',
    admin: 'Сиборомин А.В.',
    service: 'Service name',
    connectedIncidents: [],
    secondPriority: 'Связанный',
  },
  {
    id: 9,
    name: 'Пример',
    firstPriority: 'Широкомасштабный',
    param: 'authorization_problem_access',
    errors: 550,
    creationDate: '27.03.2024',
    decisionTargetDate: '01.04.2024',
    admin: 'Сиборомин А.В.',
    service: 'Service name',
    connectedIncidents: [],
    secondPriority: 'Корневой',
  },
];
